using MigraDoc.DocumentObjectModel;
using MigraDoc.Rendering;
using PdfWerk.Core;
using PdfWerk.Core.Abstractions;
using PdfWerk.Core.Models;
using PdfWerk.Pdf.Fonts;
using PdfWerk.Pdf.Internal;
using PdfWerk.Pdf.Text;
using CorePageOrientation = PdfWerk.Core.Models.PageOrientation;
using CoreTextFormat = PdfWerk.Core.Models.TextFormat;
using MigraOrientation = MigraDoc.DocumentObjectModel.Orientation;

namespace PdfWerk.Pdf;

/// <summary>
/// Renders supplied text or Markdown into a new PDF using MigraDoc for layout.
/// </summary>
public sealed class PdfComposer : IPdfComposer
{
    static PdfComposer() => FileSystemFontResolver.Install();

    public PdfArtifact Create(CreateFromTextRequest request)
    {
        if (string.IsNullOrWhiteSpace(request.Content))
            throw new PdfWerkException("There is no content to render.");

        if (request.FontSize is < 5 or > 48)
            throw new PdfWerkException("Font size must be between 5 and 48 points.");

        if (request.MarginMm is < 0 or > 100)
            throw new PdfWerkException("Margin must be between 0 and 100 mm.");

        var document = BuildDocument(request);

        var renderer = new PdfDocumentRenderer { Document = document };
        renderer.RenderDocument();

        using var output = new MemoryStream();
        renderer.PdfDocument.Save(output, closeStream: false);

        return new PdfArtifact(output.ToArray(), FileNames.FromTitle(request.Title, "document"));
    }

    private static Document BuildDocument(CreateFromTextRequest request)
    {
        var document = new Document();

        document.Info.Title = request.Title ?? string.Empty;
        document.Info.Author = request.Author ?? string.Empty;
        document.Info.Comment = "Generated by PdfWerk — https://pdfwerk.com";

        var normal = document.Styles["Normal"]!;
        normal.Font.Name = request.FontFamily;
        normal.Font.Size = Unit.FromPoint(request.FontSize);
        normal.ParagraphFormat.LineSpacingRule = LineSpacingRule.Multiple;
        normal.ParagraphFormat.LineSpacing = 1.25;

        var section = document.AddSection();
        ApplyPageSetup(section, request);

        if (request.PageNumbers)
            AddFooter(section, request.FontSize);

        if (!string.IsNullOrWhiteSpace(request.Title))
            AddTitleBlock(section, request);

        if (request.Format == CoreTextFormat.Markdown)
            new MarkdownWriter(section, request.FontSize).Write(request.Content);
        else
            WritePlainText(section, request.Content);

        return document;
    }

    private static void ApplyPageSetup(Section section, CreateFromTextRequest request)
    {
        var setup = section.PageSetup;

        setup.PageFormat = request.Page switch
        {
            PagePreset.A4 => PageFormat.A4,
            PagePreset.Letter => PageFormat.Letter,
            PagePreset.Legal => PageFormat.Legal,
            PagePreset.A3 => PageFormat.A3,
            PagePreset.A5 => PageFormat.A5,
            _ => PageFormat.A4,
        };

        setup.Orientation = request.Orientation == CorePageOrientation.Landscape
            ? MigraOrientation.Landscape
            : MigraOrientation.Portrait;

        var margin = Unit.FromMillimeter(request.MarginMm);
        setup.LeftMargin = margin;
        setup.RightMargin = margin;
        setup.TopMargin = margin;
        setup.BottomMargin = margin;

        // Keep the footer clear of the body text without eating into the margin.
        setup.FooterDistance = Unit.FromMillimeter(Math.Max(8, request.MarginMm / 2));
    }

    private static void AddFooter(Section section, double fontSize)
    {
        var footer = section.Footers.Primary.AddParagraph();
        footer.Format.Alignment = ParagraphAlignment.Center;
        footer.Format.Font.Size = Unit.FromPoint(Math.Max(7, fontSize * 0.8));
        footer.Format.Font.Color = Colors.Gray;

        footer.AddText("Page ");
        footer.AddPageField();
        footer.AddText(" of ");
        footer.AddNumPagesField();
    }

    private static void AddTitleBlock(Section section, CreateFromTextRequest request)
    {
        var title = section.AddParagraph(request.Title!);
        title.Format.Font.Size = Unit.FromPoint(request.FontSize * 2.1);
        title.Format.Font.Bold = true;
        title.Format.SpaceAfter = Unit.FromPoint(request.Author is null ? 18 : 4);
        title.Format.KeepWithNext = true;

        if (string.IsNullOrWhiteSpace(request.Author))
            return;

        var byline = section.AddParagraph(request.Author);
        byline.Format.Font.Size = Unit.FromPoint(request.FontSize * 0.95);
        byline.Format.Font.Color = Colors.DimGray;
        byline.Format.SpaceAfter = Unit.FromPoint(18);
        byline.Format.KeepWithNext = true;
    }

    /// <summary>
    /// Plain text is paragraph-per-blank-line. Single newlines inside a paragraph become
    /// explicit line breaks so that pre-wrapped input keeps the shape the author gave it.
    /// </summary>
    private static void WritePlainText(Section section, string content)
    {
        var normalised = content.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
        var blocks = normalised.Split("\n\n", StringSplitOptions.None);

        foreach (var block in blocks)
        {
            if (string.IsNullOrWhiteSpace(block))
                continue;

            var paragraph = section.AddParagraph();
            paragraph.Format.SpaceAfter = Unit.FromPoint(8);

            var lines = block.Split('\n');
            for (var i = 0; i < lines.Length; i++)
            {
                paragraph.AddText(lines[i].TrimEnd());
                if (i < lines.Length - 1)
                    paragraph.AddLineBreak();
            }
        }
    }
}
